apiVersion: ENC[AES256_GCM,data:AGY=,iv:Jh+hrdgVCq/839zVuAu/b8RkUGzmeulrbGo8kbupI4Y=,tag:ApVgYeDXgjHpQrd/CfKUFQ==,type:str]
kind: ENC[AES256_GCM,data:ezO89vjO,iv:rgXObMrTRE8iXLg5rMit7tTl3bhwSFv3CUek0dSUnfw=,tag:qCAMn+q29jpOUrBEbNTbLA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:is9b0LORN+842Pre5Q==,iv:hH7gB3GRuGbjJ6YuaSz05FQjQQPo+rTC5upkDJdoX08=,tag:JF8Roka1TuJPxVsJd8jVMA==,type:str]
type: ENC[AES256_GCM,data:irzyr7MC,iv:KbELypWw0lp1BGqALRLBTmlQ9Rktf84FNqqqF9LlbqI=,tag:wlco24PvRfuGVoxx39xS6g==,type:str]
data:
    #ENC[AES256_GCM,data:C85k5wfHCUeEdgK1Kmy4dWqLhz9iuSkM5PFp/0X4hXK/gQwPBZxVExpehBxPwK8tmNNI+DO5mGtB,iv:9ubFHlV5B4Tj8ohO9EYC7UM7+hl2ZBH2tTsmkQeXRdk=,tag:4i9ZWzmhLEGycCAeOoKgUQ==,type:comment]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:e6CCNrVcdEQ7brF7F2et6w==,iv:6F85XjVqHoJZMnH8/AoSE+5hh2iXhkBgyRagDJ1+iLQ=,tag:/Wy1oDQ6+qk9t7JEdSLxXQ==,type:str]
    #ENC[AES256_GCM,data:hr30s1G34Ay3Y56WDDIrb+a3X7vd1MfGbc/pwn95OCsW1Q==,iv:yWHYkCWfTJsWxqc6gCBq2ZKL/Vfn/oHelVPNgPfXsJc=,tag:XR86NXqQ6Ak7qNAuGzlnDQ==,type:comment]
    API_KEY: ENC[AES256_GCM,data:FE92ekjXe1qMf5JmLoMFyg==,iv:yUukAHbM7co6Zql2KNB0Dab8q3sIQn1BbdpD1EmTtbk=,tag:OnS5HsJEdyJ1zD/r/eYXzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-20T07:01:45Z"
    mac: ENC[AES256_GCM,data:LTWfC/Uwrh/Ts6zcTNt18IkA+4PSsDyxkUv1yLaAhYyziEvRzEBjBxwl/rPd+o2K+X3Itc9SkAVjFkybqDHVdcUTsm+s4ZFv+YQAvX+fEYD3fFt4lxQLiwyeWXHM1UdZ4Vhtfcx3H4JNbsdzO/ZBTsml0sDYleXrgM/KrLQHQ3Q=,iv:xuLiqBjLxjB2CFIUANKKaRl7OvRrZCQp5IipuwPESRY=,tag:liXWroTydUy/9ZA3mI8enQ==,type:str]
    pgp:
        - created_at: "2025-02-20T07:01:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAyjTzuEjjdUSAQwAq5DG+vyd4M/6sUoYkOFea/6j3db148bbm3oEO7rKJuT5
            HEv5Nezx9AHbJ/ACaYJFfftZ+j+CG0Dvpa9mGDCGJiHDe5zUGGww1BmperZ0ADmv
            lYI9N5WQA7XSHe+hCD/zkqD7q1YGPdDAd7UY/5pc0Sx1nuIjTBCDp3e8VvAD8txN
            2X9jFEW5BSdKt1SHu91cXyBZkGbkTlXXkT81u/q69Gl8v2nEi953K2D3BRiB4lGz
            q746R3lwmfKx0pQOS8j+0/wDkrqjBL7PADR7bemcLr8n32obVjr3r3wZkNc3C9zb
            RSSuQheaEzgzgTmRVEgBMHlLR+x6wNv3NnbtJwCJnzIf6fn4SJzGKVutuL1r32qj
            +sE8xAJf+fAaE8AEZA/2VYfpeOT8WmuhdVR7KtRkJEn4eduElnmP8vR7yWajlJvv
            n04mEbm1J+R/7zDkxYGKdVAUtWndTVkBnDgoTFSH0E3f1s4SNIb0dBb3ku8oNjVm
            efGnu3KxnjeyRCGd/1Nn1GgBCQIQcXCiwLHZmIGu4s7MHvsBgyLNAjan4k61sCB/
            GQfdtJVts6UiYuX1Il3ci6T55RruqbJ912viqa0WcVDyoMsh7XBxUbibMC4ZBsz+
            3I/G9WKB1hILL+ZGddmYPmiDtsOgwoTtEQ==
            =zpYu
            -----END PGP MESSAGE-----
          fp: 1108544A7590A479055DED7D7AF033CEDE34AF6C
    unencrypted_suffix: _unencrypted
    version: 3.7.3
