apiVersion: v1
kind: Secret
metadata:
    name: my-app-secret
type: Opaque
data:
    # base64-encoded password (echo -n "supersecret" | base64)
    DATABASE_PASSWORD: c3VwZXJzZWNyZXQ=
    # (echo -n "some-api-key" | base64)
    API_KEY: c29tZS1hcGkta2V5
