apiVersion: v1
kind: Secret
metadata:
  name: my-app-secret
type: Opaque
data:
  DATABASE_PASSWORD: c3VwZXJzZWNyZXQ=  # base64-encoded password (echo -n "supersecret" | base64)
  API_KEY: c29tZS1hcGkta2V5 # (echo -n "some-api-key" | base64)
