name: Deploy Application

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs the job on an Ubuntu runner

    steps:
      - name: Checkout Code  # Fetches latest code from repo
        uses: actions/checkout@v2
      - name: Install SOPS and Helm  # Install dependencies
        run: |
          sudo apt -y install gpg
          curl -LO https://github.com/getsops/sops/releases/download/v3.9.4/sops-v3.9.4.linux.amd64
          sudo mv sops-v3.9.4.linux.amd64 /usr/local/bin/sops
          sudo chmod +x /usr/local/bin/sops
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
      - name: Import GPG Key
        run: |
          echo "${{ vars.GPG_PRIVATE_KEY }}" | base64 --decode > private-key.asc
          gpg --import private-key.asc
          # Get full fingerprint
          FINGERPRINT=$(gpg --list-secret-keys --with-colons | awk -F: '/fpr/{print $10; exit}')
          
          # Trust the key as 'Ultimate'
          echo "$FINGERPRINT:6:" | gpg --import-ownertrust
          
          # Ensure the key is correctly loaded
          gpg --list-secret-keys --keyid-format LONG
      - name: Encrypt Helm Secrets
        run: |
          sops -e secrets.yaml > secrets_enc.yaml
      - name: Decrypt Helm Secrets  # Decrypt secrets before deploying
        run: |
          sops -d secrets_enc.yaml > secrets_dec.yaml
          
      - name: Deploy to Kubernetes using Helm  # Deploy application
        run: |
          helm upgrade --install my-app ./my-app -f secrets_dec.yaml
      - name: Run OWASP ZAP Scan
        run: |
          git clone https://github.com/The-DevSec-Blueprint/TIWAP.git
          cd TIWAP
          docker-compose up -d
          docker pull zaproxy/zap-stable
          docker run -v $(pwd):/zap/wrk/:rw --network="host" zaproxy/zap-stable zap-baseline.py -t https://172.0.0.2:8000 -r scan-report.html
