name: Deploy Application

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs the job on an Ubuntu runner

    steps:
      - name: Checkout Code  # Fetches latest code from repo
        uses: actions/checkout@v2

      - name: Install SOPS and Helm  # Install dependencies
        run: |
          curl -LO https://github.com/getsops/sops/releases/download/v3.9.4/sops-v3.9.4.linux.amd64
          sudo mv sops-v3.9.4.linux.amd64 /usr/local/bin/sops
          sudo chmod +x /usr/local/bin/sops
          sudo apt-get update && sudo apt-get install -y gnupg2 helm

      - name: Import GPG Key  # Import private key without passphrase (decryption will use it)
        run: |
          echo "$GPG_PRIVATE_KEY" | base64 --decode > private-key.asc
          gpg --batch --yes --import private-key.asc
          rm -f private-key.asc
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Trust GPG Key  # Mark the key as trusted
        run: |
          KEY_ID=$(gpg --list-secret-keys --keyid-format LONG | grep sec | awk '{print $2}' | cut -d'/' -f2)
          echo -e "trust\n5\ny\nsave" | gpg --batch --command-fd 0 --edit-key "$KEY_ID"

      - name: List Secret Keys  # Verify key import
        run: gpg --list-secret-keys

      - name: Decrypt Helm Secrets  # Decrypt secrets before deploying
        run: |
          export SOPS_AGE_KEY="$GPG_PASSPHRASE"  # Passphrase for decryption
          sops --decrypt --input-type yaml --output-type yaml secrets_enc.yaml > secrets_dec.yaml
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Deploy to Kubernetes using Helm  # Deploy application
        run: |
          helm upgrade --install my-app ./my-app -f secrets_dec.yaml
